import { bootDom } from "./dom.js";
import { bootRefreshSeason } from "./refresh-season.js";
import { bootLive } from "./live.js";
import { bootRepaint } from "./repaint.js";
import { bootData } from "./data.js";
import { bootReadings } from "./readings.js";
import { bootHistory } from "./history.js";
import { bootRoster } from "./roster.js";
import { bootModel } from "./model.js";
import { bootRenderCore } from "./render-core.js";
import { bootRenderPages } from "./render-pages.js";
import { bootDialCycle } from "./dial-cycle.js";
import { bootPagesNav } from "./pages-nav.js";
import { bootDiagnosis } from "./diagnosis.js";
import { bootAnalysis } from "./analysis.js";
import { bootTabsMenu } from "./tabs-menu.js";

bootDom();
bootRefreshSeason();
bootLive();
bootRepaint();
bootData();
bootReadings();
bootHistory();
bootRoster();
bootModel();
bootRenderCore();
bootRenderPages();
bootDialCycle();
bootPagesNav();
bootDiagnosis();
bootAnalysis();
bootTabsMenu();
