import { bootRefreshSeason } from "./refresh-season.js";
import { bootLive } from "./live.js";
import { bootData } from "./data.js";
import { bootComponents } from "./components.js";
import { bootHistory } from "./history.js";
import { bootCharts } from "./charts.js";
import { bootForms } from "./forms.js";
import { bootRoster } from "./roster.js";
import { bootModel } from "./model.js";
import { bootRenderCore } from "./render-core.js";
import { bootRenderPages } from "./render-pages.js";
import { bootDialCycle } from "./dial-cycle.js";
import { bootPagesNav } from "./pages-nav.js";
import { bootAnalysis } from "./analysis.js";
import { bootTabsMenu } from "./tabs-menu.js";

bootRefreshSeason();
bootLive();
bootData();
bootComponents();
bootHistory();
bootCharts();
bootForms();
bootRoster();
bootModel();
bootRenderCore();
bootRenderPages();
bootDialCycle();
bootPagesNav();
bootAnalysis();
bootTabsMenu();
