/* THE COMPONENT LEDGER.

   Keren, Sep 29 2026: "can we stay consistent in terms of components — name all the components in the app and
   then we use it and reuse it, because it seems that we are writing all over again every time we make a change."

   She is right, and the honest shape of the answer is not a document. A list of component names in a markdown
   file is a promise nobody is held to; it goes stale the first time someone is in a hurry, and this app's rule
   is zero documentation. So the ledger is COMPUTED from the source and ENFORCED by a ratchet.

   WHAT A COMPONENT IS, HERE. A CSS class is emitted by exactly one function. That function is the class's
   component, and the inventory below is derived rather than maintained — add a builder, and it names itself.
   A class emitted from two or more places is the opposite: a pattern being retyped, which is exactly what she
   was feeling.

   THE RATCHET. test/components.json records, for every shared class, how many places write it today. A class
   may lose emitters and never gain one, and a class that is not in the ledger may not become shared at all. So
   the debt can only shrink, and the next feature cannot quietly add to it. There is no big-bang refactor to
   finish before the rule starts working.

     node tools/components.js            the inventory and the shared list
     node tools/components.js --check    fail if anything became more duplicated
     node tools/components.js --bless    record where we are now
     node tools/components.js --doc      write docs/COMPONENTS.md from the same scan (V632)
     node tools/components.js --doc-check   fail if that page is stale

   V632, Keren: "I just want a way to look at all the components as a client, and that we will be able to have
   a shared language." The rule above stands — a hand-written list is a promise nobody is held to — and the
   page is not one: it is this scan printed to markdown, regenerated by `npm run map`, and `npm run check`
   fails if it is out of date. Derived, like MAP.md. So it cannot lie about what exists; the ledger is still
   what stops the debt growing. Two jobs, one scan. */
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..'), SRC = path.join(ROOT, 'src/js');
const LEDGER = path.join(ROOT, 'test/components.json');

const FN = /^  function ([A-Za-z0-9_$]+)\(/;

/* Where each class is written, by the function that writes it. Scoped to the two-space top level because that
   is what this app calls a function: everything deeper is a helper inside one, and counting those would report
   a component as duplicating itself. */
const CODE = [];   // V632: every comment-stripped line as {file, fn, line}, filled by scan(), read by callers()
function scan() {
  const css = fs.readFileSync(path.join(ROOT, 'src/styles.css'), 'utf8');
  /* Two characters, not three. The first cut of this used {2,} after the leading letter, which quietly meant
     three characters minimum and made every short class invisible to the ledger — .on, .up, and the whole of
     the .s0–.s5 and .f0–.f5 step families the heat and rate charts use. A ratchet with a blind spot is worse
     than none, because the blind spot is exactly where a modifier gets copied. */
  const defined = new Set([...css.matchAll(/\.([a-z][a-z0-9-]+)/g)].map(m => m[1]));
  const where = new Map();
  for (const file of fs.readdirSync(SRC).sort()) {
    let fn = '(top level)';
    /* Comments are skipped, and the reason is not tidiness. This app explains itself in prose that quotes the
       markup it is about — srcBlock's own note names the `class="src"` it replaced — so a scanner that read
       comments would report a component as its own second author and the ratchet would be measuring the
       writing rather than the code. Block state is tracked across lines because these comments run long; a
       line comment is only honoured when the line STARTS with one, so a `//` inside a URL is left alone. */
    let inBlock = false;
    for (const raw of fs.readFileSync(path.join(SRC, file), 'utf8').split('\n')) {
      let line = raw;
      if (inBlock) {
        const end = line.indexOf('*/');
        if (end < 0) continue;
        line = line.slice(end + 2); inBlock = false;
      }
      const open = line.indexOf('/*');
      if (open >= 0) {
        const close = line.indexOf('*/', open + 2);
        if (close < 0) { inBlock = true; line = line.slice(0, open); }
        else line = line.slice(0, open) + line.slice(close + 2);
      }
      if (line.trim().startsWith('//')) line = '';
      const m = FN.exec(line);
      if (m) fn = m[1];
      CODE.push({ file: file.replace(/^\d+[a-z]?-/, ''), fn, line, def: !!m });
      const blobs = [...line.matchAll(/class(?:Name)?\s*=\s*"([^"]+)"/g)].map(x => x[1]);
      for (const blob of blobs) for (const c of blob.split(/\s+/)) {
        if (!defined.has(c)) continue;
        if (!where.has(c)) where.set(c, new Set());
        where.get(c).add(file.replace(/^\d+[a-z]?-/, '') + ':' + fn);
      }
    }
  }
  return where;
}

const where = scan();
const shared = [...where].filter(([, v]) => v.size > 1).sort((a, b) => b[1].size - a[1].size);
const owned = [...where].filter(([, v]) => v.size === 1);

/* THE SECOND HALF OF THE SAME QUESTION (Version 617).

   These components are wired to the document by NAME: 124 ids reached through getElementById, every call
   guarded with `if (!el) return` because any given page renders only some of them. That guard is right, and it
   is also why a name that does not exist fails in total silence \u2014 the same shape as the bug Version 473 found,
   where `if (!row) return` read a missing row as a row to skip and quietly listed six readings out of eleven.
   The audit that prompted this found #pulse-span: three lines computing a sentence about the Pulse window,
   guarded, for an element that has never existed in any version of the markup.
   So the ledger checks the wiring too. An id reached in code must be written in the markup, assigned by a
   literal in code, or belong to one of the families built by concatenation \u2014 listed here, because a short list
   that has to be maintained is honest where a check that cannot see them would not be. */
const DYNAMIC = [/^sheet-/, /^peek-row-/, /^metric-page$/];

function wiring() {
  const markup = ['src/page-body.html', 'src/page-head.html', 'src/page-tail.html']
    .filter(f => fs.existsSync(path.join(ROOT, f)))
    .map(f => fs.readFileSync(path.join(ROOT, f), 'utf8')).join('\n');
  const js = fs.readdirSync(SRC).map(f => fs.readFileSync(path.join(SRC, f), 'utf8')).join('\n');
  const reached = new Set([...js.matchAll(/getElementById\("([A-Za-z0-9_-]+)"\)/g)].map(m => m[1]));
  const dangling = [];
  for (const id of reached) {
    if (markup.includes('id="' + id + '"') || js.includes('id="' + id + '"')) continue;
    if (js.includes('.id = "' + id + '"')) continue;
    if (DYNAMIC.some(re => re.test(id))) continue;
    dangling.push(id);
  }
  return { reached: reached.size, dangling: dangling.sort() };
}

/* THE PART THAT CANNOT BE SPLIT CHEAPLY CANNOT GROW EITHER (Version 624).

   Keren: "maybe we need to work on it now before we will have to refactor the entire app 200 versions from
   now." The Analysis tab moved out in this version because it was clean to move. What is left is one
   1,270-line function whose five sections share a closure, and lifting those apart is the riskiest surgery in
   the app for a payoff no reader or test would notice.
   So it is not split \u2014 it is CAPPED. Every top-level function's length is recorded, and a function may shrink
   and never grow. Her worry is then handled by a rule rather than by a heroic afternoon: the next feature
   physically cannot make the big one bigger without somebody deciding to, on purpose, in a bless.
   Whole-file sizes are deliberately NOT capped. A file growing by gaining a new function is healthy; the
   thing worth stopping is one function swallowing more. */
function sizes() {
  const out = {};
  for (const file of fs.readdirSync(SRC).sort()) {
    const lines = fs.readFileSync(path.join(SRC, file), 'utf8').split('\n');
    let name = null, start = 0;
    lines.forEach((l, i) => {
      const m = FN.exec(l);
      if (m) { name = m[1]; start = i; }
      else if (name && l === '  }') { out[name] = i - start + 1; name = null; }
    });
  }
  return out;
}

/* V632: who calls a function, by the top-level function the call sits in. Same comment-stripped lines the class
   scan read, so a name quoted in prose is not a caller. A function's own body is not a caller of itself. */
function callers(name) {
  const re = new RegExp('(^|[^A-Za-z0-9_$.])' + name.replace(/\$/g, '\\$') + '\\s*\\(');
  const out = new Set();
  for (const c of CODE) if (c.fn !== name && !c.def && re.test(c.line)) out.add(c.file + ':' + c.fn);
  return [...out].sort();
}
function allFunctions() {
  const out = [];
  for (const c of CODE) if (c.def) out.push({ name: c.fn, file: c.file });
  return out;
}
function componentsDoc() {
  const byFn = new Map();
  for (const [c, v] of owned) {
    const fn = [...v][0];
    if (!byFn.has(fn)) byFn.set(fn, []);
    byFn.get(fn).push(c);
  }
  const files = fs.readdirSync(SRC).sort().map(f => f.replace(/^\d+[a-z]?-/, ''));
  const rows = [...byFn].map(([k, cs]) => {
    const [file, fn] = k.split(':');
    return { file, fn, classes: cs.sort(), used: callers(fn) };
  }).filter(r => r.fn !== '(top level)');
  rows.sort((a, b) => files.indexOf(a.file) - files.indexOf(b.file) || a.fn.localeCompare(b.fn));
  const head = (() => { try { return require('child_process').execSync('git rev-parse --short HEAD', { cwd: ROOT }).toString().trim(); } catch (e) { return '?'; } })();
  const L = [];
  L.push('# Components');
  L.push('');
  L.push('**Generated. Do not hand-edit** — run `npm run map`. `npm run check` fails if this page is stale.');
  L.push('');
  L.push('A **component** here is a function and the CSS classes only it writes. Nothing declares itself one; the list');
  L.push('is derived from the source by `tools/components.js`, the same scan that stops a pattern being retyped. So a');
  L.push('name on this page is a name you can use — in a request, a commit, a conversation — and it points at exactly');
  L.push('one function. **Owns** is the classes no other function emits. **Used by** is every top-level function that');
  L.push('calls it, by file.');
  L.push('');
  L.push(`Generated from commit \`${head}\` on ${new Date().toISOString().slice(0, 10)}. **${rows.length} components**, **${shared.length} shared patterns**.`);
  L.push('');
  let cur = null;
  for (const r of rows) {
    if (r.file !== cur) { cur = r.file; L.push(`## ${cur}`); L.push(''); L.push('| Component | Owns | Used by |'); L.push('|---|---|---|'); }
    const owns = r.classes.map(c => '`.' + c + '`').join(' ');
    const used = r.used.length ? r.used.map(u => '`' + u + '`').join(', ') : '—';
    L.push(`| **\`${r.fn}\`** | ${owns} | ${used} |`);
    if (rows[rows.indexOf(r) + 1] && rows[rows.indexOf(r) + 1].file !== cur) L.push('');
  }
  L.push('');
  /* The vocabulary: functions that own no class but are called from three or more places. `put`, `byId`,
     `histFrame` — the words every renderer speaks. They are as much the shared language as the components. */
  const seen = new Set(rows.map(r => r.fn));
  const vocab = [];
  for (const f of allFunctions()) {
    if (seen.has(f.name)) continue;
    const u = callers(f.name);
    if (u.length >= 3) vocab.push({ ...f, used: u });
  }
  vocab.sort((a, b) => b.used.length - a.used.length || a.name.localeCompare(b.name));
  L.push('## Vocabulary');
  L.push('');
  L.push('Functions that own no class of their own but are called from three or more places — the words every');
  L.push('renderer speaks. Listed most-used first.');
  L.push('');
  L.push('| Function | Lives in | Called from |');
  L.push('|---|---|---|');
  for (const v of vocab) L.push(`| **\`${v.name}\`** | ${v.file} | ${v.used.length} places |`);
  L.push('');
  L.push('## Shared patterns');
  L.push('');
  L.push('Classes written from more than one function — a pattern being retyped. The ledger (`test/components.json`)');
  L.push('records these counts and `npm run check` fails if any of them grows. This list can only shrink.');
  L.push('');
  L.push('| Class | Places | Written by |');
  L.push('|---|---|---|');
  for (const [c, v] of shared) L.push(`| \`.${c}\` | ${v.size} | ${[...v].sort().map(x => '`' + x + '`').join(', ')} |`);
  L.push('');
  return L.join('\n');
}
const DOC = path.join(ROOT, 'docs/COMPONENTS.md');
const stripDate = t => t.replace(/on \d{4}-\d{2}-\d{2}\./, 'on DATE.').replace(/commit `[0-9a-f?]+`/, 'commit `HEAD`');

const arg = process.argv[2];

if (arg === '--doc') {
  const text = componentsDoc();
  fs.writeFileSync(DOC, text);
  console.log(`wrote docs/COMPONENTS.md — ${text.split('\n').length} lines`);
  process.exit(0);
}
if (arg === '--doc-check') {
  const now = fs.existsSync(DOC) ? fs.readFileSync(DOC, 'utf8') : '';
  if (stripDate(now) !== stripDate(componentsDoc())) { console.error('COMPONENTS.md is OUT OF DATE — run: npm run map'); process.exit(1); }
  console.log('COMPONENTS.md is current');
  process.exit(0);
}

if (arg === '--bless') {
  const out = { '#functions': sizes() };
  for (const [c, v] of shared) out[c] = v.size;
  fs.writeFileSync(LEDGER, JSON.stringify(out, null, 2) + '\n');
  console.log(`recorded ${shared.length} shared classes -> test/components.json`);
  process.exit(0);
}

if (arg === '--check') {
  const past = fs.existsSync(LEDGER) ? JSON.parse(fs.readFileSync(LEDGER, 'utf8')) : {};
  const grew = [], fresh = [], shrank = [];
  for (const [c, v] of shared) {
    if (past[c] == null) fresh.push(`.${c} is written from ${v.size} places and is not in the ledger`);
    else if (v.size > past[c]) grew.push(`.${c} ${past[c]} -> ${v.size} places`);
    else if (v.size < past[c]) shrank.push(`.${c} ${past[c]} -> ${v.size}`);
  }
  for (const c of Object.keys(past)) {
    if (c === '#functions') continue;
    if (!where.has(c) || where.get(c).size === 1) shrank.push(`.${c} ${past[c]} -> 1`);
  }
  if (grew.length || fresh.length) {
    console.error('COMPONENT LEDGER — a pattern got MORE duplicated:\n');
    [...grew, ...fresh].forEach(l => console.error('  ' + l));
    console.error('\nBuild it once and call it, or if the duplication is deliberate, run: npm run comp:bless');
    process.exit(1);
  }
  /* V647: a function the ledger has never seen had NO limit — the cap is its recorded length, and a new one has
     none recorded. It now starts under a ceiling instead. V624's rule for the functions already here is
     unchanged: they may shrink and never grow. The ceiling is for what gets written next. */
  const NEW_FN_MAX = 150;
  const caps = past['#functions'] || {}, now = sizes(), longer = [];
  for (const [fn, n] of Object.entries(now)) {
    if (caps[fn] != null && n > caps[fn]) longer.push(fn + ' ' + caps[fn] + ' -> ' + n + ' lines');
    else if (caps[fn] == null && n > NEW_FN_MAX) longer.push(fn + ' is new and ' + n + ' lines (a new function starts at most ' + NEW_FN_MAX + ')');
  }
  if (longer.length) {
    console.error('SIZE \u2014 a function got longer:\\n');
    longer.forEach(l => console.error('  ' + l));
    console.error('\\nSplit it, or if it has to grow, run: npm run comp:bless');
    process.exit(1);
  }

  const w = wiring();
  if (w.dangling.length) {
    console.error('WIRING \u2014 code reaches an element id that nothing ever creates:\n');
    w.dangling.forEach(id => console.error('  #' + id));
    console.error('\nEvery getElementById here is guarded, so this fails in silence. Delete the code, or add the element.');
    process.exit(1);
  }
  console.log(shrank.length
    ? `ledger ok — ${shrank.length} pattern(s) less duplicated than recorded:\n  ${shrank.join('\n  ')}\n  run: npm run comp:bless`
    : `ledger ok — ${shared.length} shared classes, none worse`);
  process.exit(0);
}

const byFn = new Map();
for (const [c, v] of owned) {
  const fn = [...v][0];
  if (!byFn.has(fn)) byFn.set(fn, []);
  byFn.get(fn).push(c);
}
const comps = [...byFn].filter(([, cs]) => cs.length >= 2).sort((a, b) => b[1].length - a[1].length);
console.log(`COMPONENTS — a builder and the classes only it writes (${comps.length})\n`);
for (const [fn, cs] of comps) console.log('  %s\n      %s', fn.padEnd(34), cs.map(c => '.' + c).join(' '));
const w = wiring();
console.log('\nWIRING \u2014 %d ids reached in code, %d created nowhere%s\n', w.reached, w.dangling.length,
  w.dangling.length ? ': ' + w.dangling.map(i => '#' + i).join(', ') : '');
console.log(`\nSHARED — written from more than one place (${shared.length})\n`);
for (const [c, v] of shared) console.log('  .%s %s', c.padEnd(20), String(v.size).padStart(2) + ' places');
